# Generated by Django 4.2.4 on 2023-10-28 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colegios',
            fields=[
                ('rbd', models.IntegerField(primary_key=True, serialize=False)),
                ('rut_colegio', models.CharField(max_length=45)),
                ('nombre', models.CharField(max_length=45)),
                ('region', models.CharField(max_length=45)),
                ('comuna', models.CharField(max_length=45)),
                ('dependencia', models.CharField(max_length=45)),
                ('fecha_ingreso', models.DateField()),
                ('monto_plan', models.IntegerField()),
                ('mes_facturacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('idfacturas', models.IntegerField(primary_key=True, serialize=False)),
                ('total', models.IntegerField()),
                ('nota_credito', models.IntegerField()),
                ('fecha_emision', models.DateField()),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='facturacion_app.colegios')),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('rut', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('correo', models.EmailField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('idPagos', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_pago', models.DateField()),
                ('estado_pago', models.CharField(max_length=45)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='facturacion_app.facturas')),
            ],
        ),
        migrations.AddField(
            model_name='colegios',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colegios', to='facturacion_app.trabajador'),
        ),
    ]
