# Generated by Django 4.2.4 on 2023-10-28 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='password',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
