# Generated by Django 4.2.4 on 2023-10-28 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion_app', '0002_trabajador_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colegios',
            name='mes_facturacion',
        ),
        migrations.CreateModel(
            name='Cuotas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuotas', models.IntegerField()),
                ('fecha_cuota', models.DateField()),
                ('monto_cuota', models.IntegerField()),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='facturacion_app.colegios')),
            ],
        ),
    ]
