# Generated by Django 4.2.4 on 2023-10-29 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion_app', '0003_remove_colegios_mes_facturacion_cuotas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colegios',
            name='comuna',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='colegios',
            name='dependencia',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='colegios',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='colegios',
            name='region',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='colegios',
            name='rut_colegio',
            field=models.CharField(max_length=100),
        ),
    ]
