# Generated by Django 4.2.4 on 2023-10-31 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion_app', '0004_alter_colegios_comuna_alter_colegios_dependencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturas',
            name='nota_credito',
            field=models.CharField(max_length=40),
        ),
    ]
