# Generated by Django 4.2.4 on 2023-11-12 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion_app', '0005_alter_facturas_nota_credito'),
    ]

    operations = [
        #migrations.RemoveField(
            #model_name='pagos',
            #name='idPagos',
        #),
        #migrations.AddField(
            #model_name='pagos',
            #name='id',
            #field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            #preserve_default=False,
        #),
    ]
