# Generated by Django 4.2.4 on 2023-11-12 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion_app', '0006_remove_pagos_idpagos_pagos_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturas',
            name='estado_pago',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='facturas',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Pagos',
        ),
    ]
